import "dotenv/config";
import express from "express";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadRagData, retrieveCandidates } from "./lib/rag.js";
import { warmupEmbedder } from "./lib/embedder.js";
import { rerankWithLLM } from "./lib/rerank.js";
import { isSensitive } from "./lib/sensitivity.js";
import { summarizeFeedback } from "./lib/feedback.js";
import { inferRoleFromText } from "./lib/roleinfer.js";
import { generateFirstWinTasksLLM } from "./lib/firstwin.js";
import { cleanDisplayName } from "./lib/displayname.js";
import { roleFit, buildFitJitterTable } from "./lib/rolefit.js";
import { roleConnectorRates } from "./lib/affinity.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load the shared taxonomy (sets globalThis.TAXONOMY) — same file the browser uses.
await import("./public/taxonomy.js");
const { CONNECTORS, ROLES, FALLBACK_INTENTS } = globalThis.TAXONOMY;

const app = express();
app.use(express.json());
app.use(express.static(path.join(__dirname, "public")));

const PORT = process.env.PORT || 3000;
const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY || "";
const OPENROUTER_MODEL = process.env.OPENROUTER_MODEL || "deepseek/deepseek-chat";

/* ============================ RAG CATALOG =================================
   Full MCP registry (data/catalog.json + data/embeddings.json), generated by
   `npm run ingest` + `npm run build-index`. Powers the free-text path only —
   role bundles keep using the small curated CONNECTORS catalog. Missing files
   -> RAG is null and free-text falls back to the curated keyword matcher;
   never crashes. */
const RAG = loadRagData(fs, path.join(__dirname, "data", "catalog.json"), path.join(__dirname, "data", "embeddings.json"));
if (!RAG) {
  console.log(
    "\n  ⚠ RAG catalog not found — run `npm run ingest && npm run build-index` to enable full-registry search.\n" +
      "    Falling back to the curated keyword matcher for free-text.\n"
  );
}
// Pre-warm the local embedding model at boot (not on the first live request).
// Only bother if there's actually a catalog to search against.
const embedderReady = RAG ? warmupEmbedder() : Promise.resolve(null);

// Merged display lookup for events/metrics: registry connectors render with
// their registry title (generic icon), curated connectors win where both
// exist. This is what makes a RAG-surfaced connector's funnel events record
// and render instead of being silently dropped or crashing the metrics table.
const DISPLAY = {};
if (RAG) for (const [id, s] of RAG.catalogById) DISPLAY[id] = { name: cleanDisplayName(s), ico: "icons/plug.svg" };
for (const [id, c] of Object.entries(CONNECTORS)) DISPLAY[id] = { name: c.name, ico: c.ico };

/* ============================ EVENT STORE ================================
   Funnel stages, in order. Everything is an in-memory event:
   { ts, stage, connectorId, role, surface, live }
   Seeded with realistic baseline data on boot (live:false); live events
   posted from the running app append on top (live:true) — see `live` below,
   which lets the dashboard show "this session" movement distinct from the
   large seeded baseline. Thumbs up/down are a SEPARATE feedback event type,
   not a funnel stage — kept out of STAGES so they never render as a funnel
   bar or get counted toward conversion. */
const STAGES = ["recommended", "clicked", "signed_up", "connected", "activated"];
const FEEDBACK_STAGES = ["feedback_up", "feedback_down"];
const events = [];

// Deterministic RNG so the seeded baseline looks the same every run.
function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(42);
const ROLE_KEYS = Object.keys(ROLES);
const SURFACES = ["onboarding", "in_chat"];

// Per-connector "appeal" so some convert much better than others (realistic).
const APPEAL = {}; Object.keys(CONNECTORS).forEach((id) => (APPEAL[id] = 0.25 + rand() * 0.5));

// Per-(role, connector) fit multiplier for the flywheel (lib/rolefit.js) —
// built from the SAME seeded rand() sequence, right after APPEAL and before
// seedBaseline() consumes rand() itself, so the whole seed stays
// deterministic run-to-run (same principle as the mulberry32(42) seed above).
const FIT_JITTER = buildFitJitterTable(ROLE_KEYS, Object.keys(CONNECTORS), rand);

// Stable id per event, assigned in push() below — lets the dashboard diff
// "seen before" vs "new since last poll" for the activity ticker (Task 5/7).
let nextEventId = 1;

function seedBaseline() {
  const now = Date.now();
  const DAY = 86400000;
  for (let d = 13; d >= 0; d--) {
    const dayTs = now - d * DAY;
    for (const id of Object.keys(CONNECTORS)) {
      // onboarding converts materially better than in-chat — the core thesis.
      for (const surface of SURFACES) {
        const surfaceBoost = surface === "onboarding" ? 1.6 : 1.0;
        const recs = Math.round((3 + rand() * 9));
        for (let i = 0; i < recs; i++) {
          const role = ROLE_KEYS[Math.floor(rand() * ROLE_KEYS.length)];
          push(dayTs, "recommended", id, role, surface);
          // Walk down the funnel probabilistically, boosted by how well this
          // connector fits the role it was recommended to — the flywheel's
          // seed half (lib/rolefit.js). Clamped so no probability exceeds 1.
          const fit = roleFit(role, id, ROLES, FIT_JITTER);
          const ctr = Math.min(1, 0.55 * APPEAL[id] * surfaceBoost * fit);
          if (rand() < ctr) {
            push(dayTs, "clicked", id, role, surface);
            const signupRate = Math.min(1, 0.7 * fit);
            if (rand() < signupRate) {
              push(dayTs, "signed_up", id, role, surface);
              const connectRate = Math.min(1, 0.85 * fit);
              if (rand() < connectRate) {
                push(dayTs, "connected", id, role, surface);
                if (rand() < 0.6) push(dayTs, "activated", id, role, surface);
              }
            }
          }
        }
      }
    }
  }
}
function push(ts, stage, connectorId, role, surface, live = false) {
  events.push({ id: nextEventId++, ts, stage, connectorId, role, surface, live });
}
seedBaseline();

// ILLUSTRATIVE, like the rest of the seeded baseline — a handful of thumbs
// up/down per connector so the feedback panel isn't empty on first load.
// live:false (default): these are backdrop, not "this session"'s activity.
function seedFeedback() {
  const now = Date.now(), DAY = 86400000;
  for (const id of Object.keys(CONNECTORS)) {
    const upN = Math.round(rand() * 8 * APPEAL[id]);
    const downN = Math.round(rand() * 3 * (1 - APPEAL[id]));
    for (let i = 0; i < upN + downN; i++) {
      const role = ROLE_KEYS[Math.floor(rand() * ROLE_KEYS.length)];
      const surface = SURFACES[Math.floor(rand() * SURFACES.length)];
      const ts = now - Math.floor(rand() * 13 * DAY);
      push(ts, i < upN ? "feedback_up" : "feedback_down", id, role, surface);
    }
  }
}
seedFeedback();

/* ============================ FREE-TEXT RECOMMEND =========================
   Full-registry RAG: embed query -> cosine top-25 over data/catalog.json ->
   OpenRouter re-rank grounded only in those 25 -> validated ids. Falls back
   to the curated keyword matcher when there's no RAG catalog or no key, and
   to raw vector top-hits if the LLM call times out/errors (never hangs).
   Every result here is "suggested" (off by default) — only hand-curated role
   bundles (taxonomy.js) may auto-enable; see Taxonomy Methodology page. */
function fallbackMatch(text) {
  const t = (text || "").toLowerCase();
  const hits = new Set();
  for (const rule of FALLBACK_INTENTS) {
    if (rule.kw.some((k) => t.includes(k))) rule.ids.forEach((id) => hits.add(id));
  }
  return [...hits];
}

function curatedConnectorPayload(ids) {
  return ids.map((id) => {
    const c = CONNECTORS[id];
    return { id, name: c.name, ico: c.ico, cat: c.cat, desc: c.desc, why: "Matched by keyword from your request", suggested: true };
  });
}

function ragConnectorPayload(entry, why) {
  const cat = entry.installKind === "remote" ? "Remote MCP" : "MCP Server";
  const name = cleanDisplayName(entry);
  return {
    id: entry.id,
    name,
    ico: "icons/plug.svg",
    cat,
    desc: entry.description,
    why,
    suggested: true, // risk gate: RAG results never auto-enable
    // Consent gate (RAG results only, locked decision — curated bundles
    // untouched): flag finance/email-touching connectors so the client can
    // show an explicit opt-in instead of a bare toggle.
    sensitive: isSensitive({ name, cat, desc: entry.description }),
  };
}

app.post("/api/recommend", async (req, res) => {
  const { needText } = req.body || {};
  if (!needText || !needText.trim()) return res.json({ ids: [], connectors: [], source: "empty" });

  // No RAG catalog, or no key -> curated keyword fallback (locked decision:
  // the RAG path only runs when both a catalog and a key are available).
  if (!RAG || !OPENROUTER_API_KEY) {
    const ids = fallbackMatch(needText);
    return res.json({ ids, connectors: curatedConnectorPayload(ids), source: !RAG ? "fallback-noRAG" : "fallback-nokey" });
  }

  try {
    await embedderReady;
    const candidates = await retrieveCandidates(RAG, needText, 25);
    const result = await rerankWithLLM(candidates, needText, { apiKey: OPENROUTER_API_KEY, model: OPENROUTER_MODEL });

    // No picks (timeout/error/empty) -> raw vector top-hits, so free-text
    // always returns something real and fast instead of hanging or going empty.
    // Vector fallback is already sorted by retrieval score (see topK) —
    // slicing to 4 is "top 4 by score", matching the LLM path's MAX_PICKS.
    const picks = result?.picks?.length ? result.picks : candidates.slice(0, 4).map((c) => ({ id: c.id, why: "" }));
    const byId = new Map(candidates.map((c) => [c.id, c]));
    const connectors = picks.map((p) => ragConnectorPayload(byId.get(p.id), p.why));

    return res.json({
      ids: connectors.map((c) => c.id),
      connectors,
      source: result?.picks?.length ? "rag-llm" : "rag-vector-fallback",
      model: OPENROUTER_MODEL,
      searched: RAG.count,
      candidatesCount: candidates.length,
      picked: connectors.length,
    });
  } catch (e) {
    const ids = fallbackMatch(needText);
    return res.json({ ids, connectors: curatedConnectorPayload(ids), source: "fallback-error", error: String(e.message) });
  }
});

/* ============================ ROLE INFERENCE ==============================
   Lets a user skip the role-picker grid and just describe themselves — the
   LLM infers one of the six curated ROLES, validated against that exact key
   set (anti-hallucination gate, same pattern as the recommend re-rank).
   Graceful fallback: no RAG/key/timeout/no-match -> { role: null } so the
   client falls through to the existing plain free-text (RAG-only) path. */
app.post("/api/infer-role", async (req, res) => {
  const { text } = req.body || {};
  if (!text || !text.trim() || !OPENROUTER_API_KEY) return res.json({ role: null });
  try {
    const result = await inferRoleFromText(text, ROLES, { apiKey: OPENROUTER_API_KEY, model: OPENROUTER_MODEL });
    if (!result) return res.json({ role: null });
    return res.json({ role: result.role, title: ROLES[result.role].title });
  } catch (e) {
    return res.json({ role: null, error: String(e.message) });
  }
});

/* ============================ FIRST-WIN GAP-FILL ==========================
   Hybrid (locked decision): the client builds the "day one" task card from
   curated FIRST_WINS templates first (lib/firstwin.js buildFirstWinTasks, no
   network call). Only when that produces nothing — the enabled set is all
   registry/RAG connectors with no template — does it call here for an LLM
   fill, so the common curated-role demo path never makes an extra LLM call
   at the post-connect climax. */
app.post("/api/first-win", async (req, res) => {
  const { connectors } = req.body || {};
  if (!Array.isArray(connectors) || !connectors.length || !OPENROUTER_API_KEY) {
    return res.json({ tasks: [] });
  }
  try {
    const tasks = await generateFirstWinTasksLLM(connectors, { apiKey: OPENROUTER_API_KEY, model: OPENROUTER_MODEL });
    return res.json({ tasks: tasks || [] });
  } catch (e) {
    return res.json({ tasks: [], error: String(e.message) });
  }
});

/* ============================ ROLE AFFINITY ===============================
   Flywheel — how well the event data (seeded + live) justifies a role's
   curated bundle. Pure aggregation (lib/affinity.js) over the same `events`
   store metrics/funnel use, scoped to ONE role. Called from app.js right
   after a role bundle renders (see pickRole -> loadAffinity in app.js). */
app.get("/api/affinity", (req, res) => {
  const { role } = req.query;
  if (!role || !ROLE_KEYS.includes(role)) return res.json({});
  return res.json(roleConnectorRates(events, role));
});

/* ============================ EVENT CAPTURE ============================= */
app.post("/api/events", (req, res) => {
  const batch = Array.isArray(req.body) ? req.body : [req.body];
  let n = 0;
  for (const e of batch) {
    if (!e || (!STAGES.includes(e.stage) && !FEEDBACK_STAGES.includes(e.stage)) || !DISPLAY[e.connectorId]) continue;
    // live:true — this event came from a real click just now, distinct from
    // the seeded baseline (seedBaseline never passes this arg, so it's false).
    push(Date.now(), e.stage, e.connectorId, e.role || "unknown", e.surface || "onboarding", true);
    n++;
  }
  res.json({ ok: true, recorded: n });
});

/* ============================== METRICS ================================
   Optional filters: ?connector=hubspot&role=sales&surface=onboarding */
app.get("/api/metrics", (req, res) => {
  const { connector, role, surface } = req.query;
  const rows = events.filter(
    (e) =>
      (!connector || e.connectorId === connector) &&
      (!role || e.role === role) &&
      (!surface || e.surface === surface)
  );

  const funnel = Object.fromEntries(STAGES.map((s) => [s, 0]));
  const liveSummary = Object.fromEntries(STAGES.map((s) => [s, 0]));
  const byRole = {}, bySurface = {}, byConnector = {};
  const DAY = 86400000, now = Date.now();
  const series = {}; // dayIndex -> signed_up count (the "leads" line)

  for (const e of rows) {
    // feedback_up/feedback_down are a separate event type, not a funnel
    // stage (see FEEDBACK_STAGES) — skip them here, summarized below instead.
    if (!STAGES.includes(e.stage)) continue;
    funnel[e.stage]++;
    // "Live this session" — the seeded baseline never sets live:true, so this
    // isolates a demo user's own clicks from the ~8k-event backdrop.
    if (e.live) liveSummary[e.stage]++;
    if (e.stage === "signed_up") {
      (byRole[e.role] ||= { signed_up: 0 }).signed_up++;
      (bySurface[e.surface] ||= { recommended: 0, signed_up: 0 }).signed_up++;
      const dayIdx = Math.floor((now - e.ts) / DAY);
      series[dayIdx] = (series[dayIdx] || 0) + 1;
    }
    if (e.stage === "recommended") (bySurface[e.surface] ||= { recommended: 0, signed_up: 0 }).recommended++;
    if (e.stage === "recommended" || e.stage === "signed_up") {
      byConnector[e.connectorId] ||= { name: DISPLAY[e.connectorId].name, ico: DISPLAY[e.connectorId].ico, recommended: 0, signed_up: 0 };
      byConnector[e.connectorId][e.stage]++;
    }
  }
  // bySurface conversion (the headline: onboarding vs in-chat)
  for (const s of Object.keys(bySurface)) {
    const o = bySurface[s];
    o.conversion = o.recommended ? o.signed_up / o.recommended : 0;
  }
  // per-connector conversion table
  const connectorTable = Object.entries(byConnector)
    .map(([id, o]) => ({ id, ...o, conversion: o.recommended ? o.signed_up / o.recommended : 0 }))
    .sort((a, b) => b.signed_up - a.signed_up);

  // 14-day leads series (oldest -> newest)
  const seriesArr = [];
  for (let d = 13; d >= 0; d--) seriesArr.push({ day: d, leads: series[d] || 0 });

  res.json({
    generatedAt: now,
    funnel,
    stages: STAGES,
    conversionOverall: funnel.recommended ? funnel.connected / funnel.recommended : 0,
    activationRate: funnel.connected ? funnel.activated / funnel.connected : 0,
    netNewLeads: funnel.signed_up,
    byRole,
    bySurface,
    connectorTable,
    series: seriesArr,
    // This session's own activity, isolated from the seeded baseline — see
    // the `live` flag on events. Same filters as everything else above.
    liveSummary,
    feedback: summarizeFeedback(rows),
    // Filter-dropdown options: only connectors with actual events, not the
    // full registry — keeps the dropdown usable while still covering any
    // RAG-surfaced connector a demo actually connects.
    connectors: Object.fromEntries(connectorTable.map((c) => [c.id, { name: c.name, ico: c.ico }])),
  });
});

app.get("/api/health", (_req, res) =>
  res.json({
    ok: true,
    llm: OPENROUTER_API_KEY ? "enabled" : "fallback-only",
    model: OPENROUTER_MODEL,
    events: events.length,
    rag: RAG ? { enabled: true, catalogSize: RAG.count } : { enabled: false },
  })
);

app.listen(PORT, () => {
  console.log(`\n  Multify onboarding prototype running:`);
  console.log(`  → Recommender:  http://localhost:${PORT}/`);
  console.log(`  → Dashboard:    http://localhost:${PORT}/dashboard.html`);
  console.log(`  → LLM engine:   ${OPENROUTER_API_KEY ? "ENABLED (" + OPENROUTER_MODEL + ")" : "fallback keyword matching (no OPENROUTER_API_KEY set)"}`);
  console.log(`  → RAG catalog:  ${RAG ? "ENABLED (" + RAG.count + " servers)" : "DISABLED (run npm run ingest && npm run build-index)"}\n`);
  if (RAG) embedderReady.then(() => console.log("  → Embedding model pre-warmed and ready.\n"));
});
